### ISSUE TITLE
Doc update

### ISSUE THREAD

**Issue by sfc-gh-phoran** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#4]
Your ReadMe doesn't list Snowflake as a supported DB platform, but I can clearly see it in the code.  Is it supported, or not yet?

**Comment by markddrake** [comment]
Snowflake is in the Experimental phase at the moment. I have transaction in progress that will bring it _much_ closer to production. That said the current implementation is 100% SQL based, which means that it uses SQL based inserts to upload data. After talking about this with Benoit and others at Snowflake I'm working on an alternative version that would bypass the SQL insert operations and create CSV files on AWS etc that could then be loaded using COPY. However this will take a little longer.
Would love to get some feedback as to how you might use Yadamu (eg Sources, Volumes etc).

**Comment by sfc-gh-phoran** [comment]
Thanks Mark,
Snowflake is new to the Federal marketplace, and we already have DOZENS of potential customers are coming from Oracle, SQLServer, Teradata, or AWS Redshift environments.  The pain associated with migrating the DDL and data is always a question that arises. We’re fighting the “inertia” of existing legacy database platforms.
We’re trying to build out a Professional Services practice around that, but if this tooling does what it claims to do it could become a key component of that and help eliminate barriers to Snowflake adoption.  And that’s just Federal.  Now let’s talk State/Local govt and commercial enterprises, and the potential user base grows exponentially…

I’m not saying you should monetize this work, but you should monetize this work.

PAUL HORAN
Sr. Solution Architect – US Federal

MOBILE  +1 571 643 3710<applewebdata://D9FDE66D-2BBA-43B2-BE12-0DB0917DAD08/tel+15716433710>
EMAIL  paul.horan@snowflake.com<mailto:paul.horan@snowflake.com>


[https://www.snowflake.com/wp-content/themes/snowflake/img/snowflake-logo-blue@2x.png]

**Comment by markddrake** [comment]
Snowflake is now considered production ready. For loading data into snowflake you may want to look at the Yadamu's ability to stage data files to AWS and Azure which can generate CSV files that can then be (manually) ingested using snowflakes PUT operator
