### ISSUE TITLE
Provide Pre-Configured Docker image for running Yadamu Command Line.

### ISSUE THREAD

**Issue by markddrake** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#40]

**Comment by markddrake** [comment]
Added new dockerfile  docker/bin/yadamuRuntime

To use

1.  Build Environment: 
```
docker build -t  yadamu/environment:latest . -f docker/dockerfiles/environment --no-cache --progress=plain
```

2. Build from Local Storage:
```
docker build -t  yadamu/base:latest . -f docker/dockerfiles/yadamu
```

3: Create a Volume to manage output:
```
docker volume create YADAMU-MNT-01
```

4. Start Runtime
```
docker run --name RUNTIME-01 --memory="16g" --network YADAMU-NET -d -vYADAMU_01_MNT:/usr/src/YADAMU/mnt  yadamu/docker:latest
```

Optionally if you want to be able to access the output directory from a windows development environment 

1.  Create a Docker SMB Server
```
docker run --name YADAMU-SMB -m 512m -it -p 139:139 -p 445:445 -p 137:137/udp -p 138:138/udp -vYADAMU_01_MNT:/mount -d dperson/samba -p -s "work;/mount;yes;no;yes" -n
```
2. Map the shared volume to a windows drive (assuming you want to map to drive "Y" and your docker host is called "docker-host":
```
net use y: \\docker-host\work
```

**Comment by ljrickwood** [comment]
There appears to be a step missing. No docker:latest is produced.

**Comment by markddrake** [comment]
@ljrickwood : Thanks for picking this up.. Instructions have been updated.
