### ISSUE TITLE
YadamuExport - should prompt password when working with Postgres

### ISSUE THREAD

**Issue by ljrickwood** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#56]
Running YadamuExport against a Postgres database should have caused the script to prompt for the DB user password. The script did not prompt for the password.

`root@b44c0e301b20:/usr/src/YADAMU# yadamuExport rdbms=postgres username=lrickwood database=demo from_user=\"bookings\" hostname=192.168.2.60 sql_trace=trace.sql overwrite=true`

**Comment by markddrake** [comment]
This issue was specific to using Postgres. Interactive Password Entry  is now enabled in the Postgres Driver.
