### ISSUE TITLE
PostgresDBI: Add support for POINT and other spatial related datatypes, when PostGIS extension is not present.

### ISSUE THREAD

**Issue by ljrickwood** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#57]
Yadamu tests for the presence of the Postgres PostGIS extension and assumes that the Point datatype is not supported if PostGIS is not installed. The Point type is supported in the absence of the extension.

ie no PostGIS extension

`demo=# \dx
List of installed extensions
Name | Version | Schema | Description
plpgsql | 1.0 | pg_catalog | PL/pgSQL procedural language
(1 row)`
`demo=# \dx+
Objects in extension "plpgsql"
Object description
function plpgsql_call_handler()
function plpgsql_inline_handler(internal)
function plpgsql_validator(oid)
language plpgsql`

But tables with the point datatype;
`demo=# \d airports_data
                Table "bookings.airports_data"
    Column    |     Type     | Collation | Nullable | Default 
 airport_code | character(3) |           | not null | 
 airport_name | jsonb        |           | not null | 
 city         | jsonb        |           | not null | 
 coordinates  | point        |           | not null | 
 timezone     | text         |           | not null | 
Indexes:
    "airports_data_pkey" PRIMARY KEY, btree (airport_code)
Referenced by:
    TABLE "flights" CONSTRAINT "flights_arrival_airport_fkey" FOREIGN KEY (arrival_airport) REFERENCES airports_data(airport_code)
    TABLE "flights" CONSTRAINT "flights_departure_airport_fkey" FOREIGN KEY (departure_airport) REFERENCES airports_data(airport_code)`

**Comment by markddrake** [comment]
When using YADAMU it is **STRONGLY** recommended that the PostGIS extension be installed before attempting to work with spatial data types. YADAMU transports spatial data using the OpenGIS groups WKT and WKB formats, or as GeoJSON. The PostGIS extension for Postgres enables generation and ingestion of these formats.

During Import operations, Yadamu will map spatial data according to the following rules when PostGIS is not present.

- Spatial data in WKT/EWKT format will be stored as TEXT
- Spatial Data in WKB/EWKB format will be stored as BYTEA
- Spatial Data in GeoJSON format will stored as JSONB. 

If a Yadamu Import operation targets a pre-existing table, the operation could fail if there is a mismatch between the data types Yadamu is expecting and the data types in the pre-existing table.

**Comment by ljrickwood** [comment]
OK, that works for me.
